### ISSUE TITLE
No masks found. Please lower cons.

### ISSUE THREAD

**Issue by DG1038286** [YijunBao/Shallow-UNet-Neuron-Segmentation_SUNS#10]
Quick question on what "Please lower cons." means?

Here is the terminal log of what I get:
```
separate Neurons         : Used  0.140590 s,  4.134999 ms/frame,      18 segmented neurons.
unique_neurons1          : Used  0.046864 s,  1.378354 ms/frame,       2 segmented neurons.
group_neurons            : Used  0.053538 s,  1.574643 ms/frame,       2 segmented neurons.
piece_neurons_IOU        : Used  0.024630 s,  0.724421 ms/frame,       2 segmented neurons.
piece_neurons_consume    : Used  0.046864 s,  1.378354 ms/frame,       1 segmented neurons.
No masks found. Please lower cons.
refine_seperate          : Used  0.000000 s,  0.000000 ms/frame,       1 segmented neurons.
Total time               : Used  0.312486 s,  9.190770 ms/frame,       1 segmented neurons.
Post-Processing time: 0.328106 s, 7.291243 ms/frame
Total time: 1.781648 s, 39.592181 ms/frame
{'Recall': 0, 'Precision': 0, 'F1': 0}
```

This was running inference on the pretrained model as given, with our data.

**Comment by YijunBao** [comment]
First, the major result is `No masks found`, which means that SUNS did not find any neuron in the video. If you used our pretrained model and applied directly to your video, and your video has very different imaging conditions from the demo videos, this can happen. We expect users to train the CNN models and optimize post-processing parameters using their own videos, so that the imaging condition is consistent with their test videos. 
Second, `cons` is a post-processing paramter that can be optimized in training. The optimal cons is often larger than 1 when the frame rate of the video is high, but it may eliminate all masks, which leads to the result `No masks found`. It is possible to retain some masks when lower `cons` or simply set it to be 1. In your case, you used the parameters optimized for the demo videos, so they may do a poor job for your videos.

**Comment by DG1038286** [comment]
So, `list_cons = list(range(1, 8, 1))` states that frames 1 to 8 (one right after the other) have active neurons? I'm not sure I completely understand. What do you define as high frame rate (we are at 15 Hz)?

**Comment by YijunBao** [comment]
I think high frame rate indicates that the calcium transient can show a clear rise-decay pattern, rather than a single-frame activity. Therefore, it depends on the decay time of the calcium indicator. If the period of the recording (inverse of frame rate) is shorter than the decay time of the calcium indicator, then I think the video has high frame rate.
