### ISSUE TITLE
TensorFlow 1 causing F1 zero	?

### ISSUE THREAD

**Issue by DG1038286** [YijunBao/Shallow-UNet-Neuron-Segmentation_SUNS#12]
I'm not sure if anyone else is experiencing this, but my F1, recall, and precision were all being evaluated to zero when running tensorflow-gpu (1.15). I tried to test the tensorflow 2 installation script but it gave some code errors due to deprecated code. I also tried retraining it multiple times after the initial training (as documented in the installation instructions), but it kept giving issues.

I was able to run it without GPU and it gave me proper F1 scores and more segmented neurons. I wasn't sure if this was an issue experienced elsewhere? I've tested this method on multiple computers with GPUs (RTX 3090, RTX A4000 (Quadro), GTX 1050, and Quadro P4000). Thanks

**Comment by YijunBao** [comment]
It is interesting to hear that the outputs are different when running on GPU or CPU. I don't know the reason, but I think you can check a few things. 
1. What are the output masks under the folder `output_masks`? When F1=0, is the output masks empty?
2. How does the loss vary during training? You can find the loss information under the folder `training output`.
3. What are the optimized post-processing parameters? Are they always the first element in the list of searched parameters? You can find them under the folder `output_masks` -> `Optimization_Info_{}.mat` -> `Params`.
4. If you run the test script on CPU using the training result from GPU, or if you run the test script on GPU using the training result from CPU, what result will you get?
There should be something wrong in one of the steps, so looking at the intermediate output can give better understanding of when the discrepancy occurs.

**Comment by 1209657459** [comment]
I had the same problem with RTX3090,tensorflow==1.15.
The first thing I found was that the output_mask was all 1 and its size was 1x120x88, then I found that all the f1s were 0.
So I tried to train again, the loss was decreasing but with the increase of epoch there was a loss=nan. the result was the same as the first time.
I don't know what is causing this.
<img width="604" alt="image" src="https://user-images.githubusercontent.com/109506063/179460205-cd313534-6ebd-4c93-af85-25da7ccd852b.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/109506063/179460836-2fdb78f9-ff9b-4b8d-98cd-2a9731ecb337.png">

**Comment by YijunBao** [comment]
@1209657459 The training failed apparently. It seems the neural network predicts every pixel as 1. I have not seen this before, but I have seen that neural network predicts every pixel as 0 multiple times. Have you tried training on CPU? In addition, could you please check the temporal masks under the folder `temporal_masks(3)` and the pre-processed videos under the folder `network_input`? Do they have a good frame-by-frame matching?

**Comment by 1209657459** [comment]
@YijunBao 
Glad to hear back from you!
Training on the cpu is ongoing and it's going a lot slower than I expected, it's been going on for about 6 hours.
I just checked the two folders and for the most part they match each other, occasionally there are some neurons that don't show up on the mask (rarely, maybe it's the dataset).
Maybe my problem is not caused by this.
Attached below are a few frames from YST_part11, is this normal?
I hope the cpu training will bring a good result.
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/109506063/179536572-58865e8f-c428-4bd2-ac4f-15b8b71f82fe.png">
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/109506063/179536720-a27b56ce-dd72-4cdd-b089-3f6eaba51b46.png">
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/109506063/179535546-b9be7460-15b8-487a-8340-48b8fecabf61.png">

**Comment by YijunBao** [comment]
@1209657459 Yes, the images you shown matched well, so the problem likely comes from training. I understand that training on CPU is slow, so no one really wants to do this practically. When I test the training on CPU, I usually decrease the number of epochs to 20 or 50 to save time. Do you observe similar nan loss when training with CPU?
I just reran the pipeline on my computer using NVIDIA Titan RTX, and it gave similar F1 than what I showed on the readme. Maybe you can also try installing exact same environment with mine using `environment_suns_fix_version.yml`.

**Comment by 1209657459** [comment]
@YijunBao 
When running the program on the cpu, there is no abnormal loss.
The previous environment used was "environment_suns.yml"
Later I will reinstall the environment you suggested and try it again using gpu.
But I need to get some sleep now.
Looking forward to waking up with good results.
Thanks again for your reply!

**Comment by 1209657459** [comment]
@YijunBao 
The training on the cpu worked, F1=0.8157, and the size of the final output Masks was normal.
This makes me wonder why it works on the CPU but not on the GPU.
And I have a lot of conflicts when I install the "environment_suns_fix_version.yml" .
This still prevents me from using the GPU for training, can you give me some advice?

**Comment by YijunBao** [comment]
So @1209657459 had the same result as @DG1038286 . I don't understand either why GPU does not work. If the CPU training works well, then the problem must be from the GPU or CUDA. What are your versions of CUDA related packages? 
I uploaded a new `environment_suns_exact.yml` to the `installation` folder. This file contains all the exact versions in my environment. Perhaps you can try installing this exact environment, and see if it works.

**Comment by 1209657459** [comment]
@YijunBao 
Just now I successfully completed training on GPU, which is indeed the reason for the environment. My previous tests were on RTX3060+CUDA11.6 and RTX3060+CUDA11.6. Thank you very much for providing the exact version of the environment.
There are some small notes during the installation of "environment_suns_exact.yml".
(1)You can use the "conda env export > environment_suns_exact.yml --no-builds" command to remove the second equal sign and suffix (this is specific machine information, you need to delete it to install this environment on a different computer)
(2) "The conflict is caused by: The conflict is caused by:
    The user requested tensorflow-estimator==2.2.0
    nvidia-tensorflow 1.15.5+nv21.10 depends on tensorflow-estimator==1.15.1". So I changed "tensorflow-estimator==2.2.0" to "tensorflow-estimator". Then the environment was successfully installed.
(3)And there are some problems with the "keras" version. When running the code, "ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'" appears. I solved it by "pip install keras==2.3.1".

Thanks a lot for your help!

**Comment by YijunBao** [comment]
@1209657459 Thank you very much for sovling the issue. Version compatibility is indeed a big problem in python programing. It has caused several issues. I also had similar issues when I started this program. I don't understand a lot of the details. For example, when I install `tensorflow-gpu = 1.15` but did not specify the version of tensorflow-estimator, Anaconda will automatically install tensorflow-estimator = 2.1 or 2.2 (I forgot which), so I need to manually use `pip install tensorflow-estimator == 1.15.1`. This is why you see `tensorflow-estimator==1.15.1` under `pip`, but I don't know why it is not reflected to your installed environment. Another mystery from my side is, as you can see from `environment_suns_exact.yml`, `tensorboard` and `tensorflow-base` are 1.15.0, but `tensorflow` and `tensorflow-gpu` are 1.13.2 under pip. But I remember I tried to force installing tensorflow-gpu = 1.15, but conda told me it is already installed. I don't know what happened. 
I think the installation should work when I submitted and published the paper, but it has more issues now as many packages have newer versions. I think I should take some time to update the best installation steps. Thank you for your help with digging into the issues.

**Comment by YijunBao** [comment]
@DG1038286 Have you solved your problem? I tried to install `environment_suns.yml` again in my computer, and it works, so the problem is machine specific. Please try uninstalling and installing packages related to tensorflow and cuda, and make sure their versions are compatible. Maybe also check the graphics card driver. Or you can try `environment_suns_tf2.yml`, which uses Tensorflow 2.6 and Python 3.9. I updated the code a little bit, so that it can run on Tensorflow 2, at least in my computer. The speed is still slower than running on Tensorflow 1.

**Comment by DG1038286** [comment]
It works! I was not having luck previously -- I tried rolling back drivers and updating to most latest as well, but that was not solving the issue (I am now back to the original driver version we were at). For me, with an RTX A4000, it works with Tensorflow 2.6 and Python 3.9 perfectly (used the environment_suns_tf2.yml file). I've attached an image in case anyone is still running into the issue and wants to know my driver and CUDA versions as well. Thank you very much for the update and help! 
![image](https://user-images.githubusercontent.com/59807888/183110137-e3a56712-1636-4212-9934-a61a2fb4d7bf.png)
