### ISSUE TITLE
the demo has something wrong

### ISSUE THREAD

**Issue by zimo-k** [YijunBao/Shallow-UNet-Neuron-Segmentation_SUNS#7]
when I run the demo of demo_train_CNN_params.py
the code stop at the last step (parameter optimization) 
but there are no error message in the terminal
the file of output mask and temp are always empty
May I ask you the cause of this problem?

**Comment by YijunBao** [comment]
My opencv version is 3.4.1. The `thresh1` should be converted to uint8 for some reason I forgot, but the values are still either 1 or 0. Are you able to pause debugging before the error line as I suggested in the previous comment? When use pause on error, you should be able to see what `thresh1` is. Another direction is you can run `cv2.connectedComponentsWithStats` directly in aother python program, and see if it can work as expected.

**Comment by DG1038286** [comment]
Yep, the OpenCV version was the issue. In my case, I ended up using 3.4.2 since it was the first I saw compatible with python 3.7 prior to reading this message, but I'm sure 3.4.1 would've worked too. Thanks for the help. 

I also had to change some restrictions in the dependencies in environment_suns.yml to prevent a bunch of package conflicts (for fissa and h5py). Since fissa version was changed, I did not copy over the core.py and neuropil.py in the installation directory  as that was causing issues -- but that may be something else (or may be resolved by simply using 3.4.1). I've pasted that yml config below for anyone else having the same issue.

```
name: suns
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.8
  - pip
  - numpy
  - h5py    #=2.10.0
  - matplotlib
  - numba
  - opencv=3.4.2
  - scikit-image
  - scikit-learn
  - scipy
  - shapely 
  # - tensorflow==1.15
  - tensorflow-gpu==1.15
  - keras
  - pip:
    - fissa #==0.7.2
    - pyfftw
    - tensorflow-estimator==1.15.1
    - py-cpuinfo
```

**Comment by YijunBao** [comment]
Thank you very much for your information and update, @DG1038286. Version compatibility is indeed an issue for the code developped years ago. We have also seen same issue for h5py, and that is why the h5py version is specified in the `environment_suns.yml`. To reduce similar issues in the future, I provided `environment_suns_fix_version.yml` with all versions specified as the versions in my computer. This file can be used instead of `environment_suns.yml`, or as a reference for sovling version compatibility issues. 
For fissa, yes, my changes are specific to v 0.7.2, so the `core.py` and `neuropil.py` cannot be used in newer version. These files aims to solve two problems in fissa v 0.7.2: redundant `separate` or `separation_prep` rerunning and limited video size to <4 GB. I see the first problem was solved in fissa v 1.0.0, but the second problem was not mentioned so far. I have not installed newer versions of fissa, so I would keep fissa == 0.7.2 in my yml file, but if the v 1.0.0 runs fine in your computer, that is a good news.

**Comment by YijunBao** [comment]
> when I run the demo of demo_train_CNN_params.py the code stop at the last step (parameter optimization) but there are no error message in the terminal the file of output mask and temp are always empty May I ask you the cause of this problem?

Sorry, I did not realize your initial question was different from the following discussions. How does the terminal look like when you define as "stop"? Does the code still utilize CPU even if the terminal does not update? If so, a possible reason is that it takes too much time in parameter optimization, so you see no progress in the terminal. You can change the ranges of the post-processing parameters you try to optimize (e.g., `list_minArea`, `list_avgArea`, `list_thresh_pmap`, and `list_thresh_COM`), as well as other fixed parameters (e.g., `list_avgArea `and `thresh_COM0`). Particularly, try increasing the lower bounds of `list_minArea` and `list_thresh_pmap`, because low minArea and low thresh_pmap can cause long post-processing time with poor results.

**Comment by zimo-k** [comment]
Thanks a lot for reading my question in detail. I have solve the problem with the following discussions. When I use opencv-python==3.4.2.17 ,the demo can correctly run very fast and have a fantastic result.
